server:
  port: 8888
  servlet:
    context-path: /myspace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myspace?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

netPhotoURLHead: https://civilis.serveo.net/myspace/photo/